
spring:
  profiles:
    active: dev



#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://sujalgangarde09:JournalApp09@cluster0.vx3iga3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#      host: cluster0.vx3iga3.mongodb.net
#      database: journaldb
#      auto-index-creation: true
#
#server:
#  port: 8080
#  servlet:
#    context-path: /journal


# application.properties has higher priority than application.yml
# And command line arguments have higher priority than application.properties that with jar file execution
# And intellij config is more priority than CLI arguments
# i.e., Intellij config > CLI arguments > application.properties > application.yml


# application.properties :-
#spring.application.name=journalApp
#spring.data.mongodb.uri=mongodb+srv://sujalgangarde09:JournalApp09@cluster0.vx3iga3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.host=cluster0.vx3iga3.mongodb.net
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true

#server,port=8080
#server.servlet.context-path=/journal

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.username=yourUsername
#spring.data.mongodb.password=yourPassword
